### ISSUE TITLE
Zop doesn't distinguish upper/lower case.

### ISSUE THREAD

**Issue by rec** [thierryvolpiatto/zop-to-char#5]
Zop's behavior is the same as zap's in this manner, but that's always disappointed me about zap.  It might well be that consistency trumps the desire for this new feature, however.

Thanks for a great program!

**Comment by thierryvolpiatto** [comment]
Tom Swirly <notifications@github.com> writes:

> Zop's behavior is the same as zap's in this manner, but that's always
> disappointed me about zap. It might well be that consistency trumps
> the desire for this new feature, however.

You can now customize case-fold-search in zop-to-char with
zop-to-char-case-fold-search, tough you should keep the default value.

Default is 'smart which mean that when you type "E" zop-to-char will use
a nil value for case-fold-search and when you type "e" it will use a
non--nil value

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rec** [comment]
Whoa, friction burns on my terminal! ;-)  Thanks for the super-fast turnaround.  And the "smart" idea is really slick.

**Comment by thierryvolpiatto** [comment]
Tom Swirly <notifications@github.com> writes:

> Whoa, friction burns on my terminal! ;-) Thanks for the super-fast
> turnaround. And the "smart" idea is really slick.

I have already implemented this in helm, so it was easy to port it here
;-)

Thanks to remind me to do this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
